# Generated by Django 2.2.3 on 2019-07-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('meaning', models.CharField(max_length=200)),
                ('reversal', models.CharField(max_length=200)),
                ('card_id', models.IntegerField()),
                ('image', models.FilePathField()),
            ],
        ),
    ]
